tap "homebrew/bundle"
tap "homebrew/core"
brew "autoconf"
brew "automake"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "cocoapods", link: false
brew "coreutils"
brew "libksba"
brew "libtool"
brew "openssl@3"
brew "pkg-config"
brew "zlib"
